# Generated by Django 5.2.2 on 2025-06-15 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='peliculas_favoritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
